
const ON_BIDING = 'ON_BIDING'
const ON_PAYING_FIRST = 'ON_PAYING_FIRST'
const ON_REPORTING = 'ON_REPORTING'
const ON_PAYING_SECOND = 'ON_PAYING_SECOND'
const ENDED = 'ENDED'
const FAILED = 'FAILED'

export { ON_BIDING, ON_PAYING_FIRST, ON_REPORTING, ON_PAYING_SECOND, ENDED, FAILED }